# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B3fmK10-j5nGwANxV4etG2BNJeYnoPIA
"""

from google.colab.patches import cv2_imshow
import cv2
History=cv2.imread("History.jpg")
Machine=cv2.imread("Machine.jpg")
Robo=cv2.imread("Robo.jpg")
cv2_imshow(History)
cv2_imshow(Machine)
cv2_imshow(Robo)

oqqora=cv2.cvtColor(History,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)
oqqora1=cv2.cvtColor(Machine,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora1)
oqqora2=cv2.cvtColor(Robo,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora2)